import {
  BriefcaseBusiness,
  CheckCircle2,
  ClipboardPenLine,
  FileText,
  Headphones,
  Languages,
  Mic2,
  PenLine,
  Shield,
} from "lucide-react";
import {
  BASIC_PRICE_USD,
  ELITE_PRICE_USD,
  ESSENTIAL_ADVANCED_PRICE_USD,
  PRO_PRICE_USD,
} from "./service-quote-pricing";

/** Shared UI strings (EN/FR) for marketing surfaces. */
export const translations = {
  en: {
    navHome: "Home",
    navTrust: "Trust",
    navServices: "Services",
    navPricing: "Pricing",
    navCapabilities: "Capabilities",
    navDelivery: "Delivery",
    navEngagement: "Engagement",
    navTestimonials: "Stories",
    navContact: "Contact",
    navLogin: "Login",
    navRegister: "Register",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    uploadEyebrow: "Confidential intake",
    uploadTitle: "Secure executive upload",
    uploadText: "Encrypted handoff for strategist review—ATS alignment and leadership narrative clarity.",
    uploadButton: "Upload document",
    uploadSuccess: "Upload completed successfully.",
    uploadError: "Upload failed. Please try again.",
    uploadHint: "PDF, DOC, DOCX · Executive-length documents.",
    uploadDropTitle: "Drop your résumé here",
    uploadDropHint: "or click to browse · confidential handling",
    uploadConfidentialLine: "Confidential executive handling · encrypted in transit",
    servicesTitle: "Curated capabilities",
    servicesSubtitle:
      "Discrete modules you can compose—each anchored to recruiter behaviour and ATS vendors in market.",
    serviceAction: "Continue",
    serviceCategory: "Line of business",
    capabilitiesTitle: "Enterprise capabilities",
    capabilitiesSubtitle: "Institutional-grade modules mapped to hiring committee expectations.",
    servicesPageTitle: "Services & intake",
    servicesPageSubtitle: "Begin with encrypted upload or explore each delivery lane.",
    pricingTitle: "Professional Career Upgrade Plans",
    pricingSubtitle:
      "Choose the right executive upgrade level for résumé, ATS, LinkedIn, and interview readiness.",
    popular: "Most selected",
    selectPlan: "Select plan",
    ctaSelectBasic: "Begin Basic studio",
    ctaSelectProfessional: "Choose Professional",
    ctaSelectElite: "Start Elite concierge",
    ctaSelectEssentialAdvanced: "Activate Essential Advanced",
    processing: "Processing…",
    deliveryProtocolsTitle: "Delivery protocols",
    deliveryProtocolsSubtitle:
      "Governed milestones from encrypted intake to ATS-safe export—repeatable for audit and scale.",
    engagementTitle: "Live engagement & momentum",
    engagementSubtitle:
      "Authenticated metrics from Neon-backed interactions—no vanity counters. Follow Resumora for release cadence.",
    engagementFollow: "Follow Resumora",
    engagementFollowing: "Following",
    engagementLike: "Like",
    engagementSave: "Save",
    engagementRequest: "Intent signal",
    engagementTrending: "Trending services",
    engagementMostLiked: "Most liked",
    engagementMostSaved: "Most saved",
    engagementMostRequested: "Most requested",
    engagementDisabled: "Engagement requires database connection (Neon).",
    testimonialsTitle: "Client outcomes",
    testimonialsSubtitle:
      "Selected feedback from executives and senior ICs after repositioning engagements.",
    trustTitle: "Trust at a glance",
    trustSubtitle:
      "Encrypted intake, governed delivery, and checkout you can explain to procurement in one sentence.",
    trustSecureDelivery:
      "Encrypted intake, governed artifacts, positive-only public signals—checkout without dark patterns.",
    trustStrip: "Greenhouse · Lever · Workday · ATS-safe PDF/DOC · Global hiring desks · EN/FR delivery",
    engagementStripTitle: "Studio momentum (typical week)",
    engagementHeatLabel: "Delivery rhythm signal",
    engagementSessionsLabel: "Intake band",
    engagementApprovalLabel: "Stakeholder approval feel",
    engagementRecommendLabel: "Would recommend (survey band)",
    engagementSignalsDisclaimer:
      "Illustrative pacing band for a premium studio week—not a live concurrent user count. Values drift slowly to reflect normal operational variance.",
    engagementDisclaimerAnalytics:
      "Aggregated, anonymized product signals (likes, saves, requests, and coarse page views)—not concurrent visitors. Values are smoothed to avoid hourly spikes.",
    engagementDisclaimerBlended:
      "Combines light real product signals with studio pacing bands when the sample is still small—not a live headcount.",
    engagementPopularLabel: "Popular lane",
    engagementTrendingChip: "Strong demand",
    engagementVerifiedReview: "Verified client note",
    engagementSessionsLabelSignals: "7-day signal band",
    engagementMicroCtaStories: "Client stories",
    engagementMicroCtaPricing: "Compare tiers",
    engagementRecentlySelected: "Selection cadence",
    engagementSatisfactionTrust: "Client satisfaction signals stay positive-only in public views—no dislike counters.",
    badgeBestValue: "Best value",
    badgeBalanced: "Balanced",
    badgeMostPopular: "Most selected",
    pricingTrustSecureLine: "Stripe-secure · encrypted intake · materials never resold.",
    pricingWorkflowTrustLine:
      "After payment you receive a concierge routing note within the SLA on your receipt.",
    pricingCompareHint:
      "All tiers deliver ATS-safe collateral. Elite adds concierge depth, LinkedIn relaunch, and rehearsal assets when the mandate is visible and time-sensitive.",
    pricingCompareTitle: "At-a-glance studio depth",
    pricingCompareLead: "Scan what changes between lanes—no procurement spreadsheet required.",
    pricingCompareExpand: "View full comparison",
    pricingCompareCollapse: "Show less detail",
    pricingEliteHighlight:
      "Elite — premium concierge delivery for leadership-level positioning.",
    pricingEssentialAdvancedHighlight:
      "Essential Advanced ($110) — fourth studio lane (far right): ATS-ready résumé upgrade with structured formatting, keywords, cover letter support, faster turnaround, and limited revisions.",
    badgeInterviewStudio: "Interview studio",
    badgeEssentialAdvanced: "Advanced studio",
    footerTagline:
      "Resumora crafts institutional-grade career collateral for leaders who cannot afford generic.",
    footerColProduct: "Product",
    footerColCompany: "Company",
    footerColLegal: "Legal",
    footerAbout: "About",
    footerServices: "Services",
    footerPricing: "Pricing",
    footerUpload: "Upload",
    footerTrust: "Trust metrics",
    footerCapabilities: "Capabilities",
    footerDelivery: "Delivery",
    footerEngagement: "Engagement",
    footerStories: "Stories",
    footerTerms: "Terms",
    footerPrivacy: "Privacy",
    footerSupport: "Support",
    footerContact: "Contact",
    footerCopy: "© 2026 Resumora. All rights reserved.",
    installPwaTitle: "Install Resumora for faster access",
    installPwaInstall: "Install app",
    installPwaDismiss: "Not now",
    navGroupOverview: "Overview",
    navGroupProduct: "Services & delivery",
    navGroupExperience: "Stories & engagement",
    navGroupSupport: "Company & support",
    sidebarNavLabel: "Studio navigation",
    footerAboutLuxury:
      "Executive resume studio — ATS-grade dossiers, bilingual EN/FR delivery, concierge cadence.",
    footerColReach: "Contact",
    footerEmail: "support@resumora.net",
    footerLiveChat: "Live chat",
    footerAutomated247: "24/7 automated acknowledgment on intake",
    footerRefund: "Refund policy",
    footerSystemPolicy: "System & platform policy",
    footerSocial: "Social",
    footerSocialPlaceholder: "Configure NEXT_PUBLIC_SOCIAL_* URLs for icons.",
    footerDockSocial: "Official channels",
    footerDockEngage: "Trust & signals",
    footerEngageShare: "Share",
    footerEngageRegister: "Register",
    footerPricingCta: "Compare plans",
    footerToolbarAria: "Resumora quick actions",
    footerShareCopied: "Link copied to clipboard.",
    footerShareFail: "Could not share. Copy resumora.net manually.",
    footerEngageBarLead:
      "Stripe-secured checkout · bilingual EN/FR · concierge delivery — positive-only public signals.",
    footerTrustChipPopular: "Most selected · Professional depth",
    footerTrustChipRecent: "Selection cadence · Professional & Elite lanes",
    footerTrustChipElite: "Best value · Elite studio lane",
    footerTrustChipSecure: "Encrypted intake · governed retention",
    footerTrustChipAi: "AI-accelerated workflow · human editorial control",
    footerTrendingPrefix: "Trending",
    footerLiveSignals: "Live product signals",
    footerConfigureNeon: "Connect Neon for live engagement rollups",
    freeTestMetaTitle: "Complimentary review",
    freeTestTitle: "Start Free Review",
    freeTestLead:
      "Select your lane, language, and scope—preview-level review only. No payment. Final delivery unlocks on a paid tier.",
    freeTestEmail: "Work email",
    freeTestService: "Service",
    freeTestLang: "Preferred language",
    freeTestPages: "Page scope",
    freeTestNotes: "Goals or role target (optional)",
    freeTestUpload: "Attach résumé/CV (PDF/DOC/DOCX)",
    freeTestOptional: "Optional",
    freeTestSubmit: "Submit review request",
    freeTestSuccess: "Received. Our team will respond with preview guidance—final files require a paid plan.",
    freeTestLimit: "One complimentary preview per email.",
    freeTestDisclaimer:
      "This complimentary review is preview intake only. It does not trigger Stripe checkout and is not full production delivery.",
    freeTestNeonError: "Server database is offline—try again after Neon is configured.",
    freeTestDuplicate: "This email has already used its complimentary review.",
    freeTestErrorGeneric: "Something went wrong. Email support@resumora.net if this persists.",
    freeTestStartCta: "Start Free Review",
    contactPageTitle: "Contact",
    contactMetaDescription: "Reach Resumora support — 24/7 coverage and secure chat.",
    contactHours247: "Support hours: 24 hours a day, 7 days a week.",
    contactAutoConfirm:
      "Configure your mail host so every sender to support@resumora.net receives an automated confirmation reply.",
    contactChatCta: "Open secure chat",
    langSwitcherAria: "Site language",
    langEnglish: "English",
    langFrench: "Français",
    minimalHomeAria: "Resumora home",
    backHome: "Back to home",
    returnHome: "Return home",
    navHomeShort: "Home",
    seoSolutionsEyebrow: "SEO · Solutions",
    heroSecureUploadShort: "Secure upload",
    pricingQuestionsTitle: "Questions before checkout?",
    pricingQuestionsSubtitle: "Concierge routing for enterprise lanes.",
    aboutTitle: "About Resumora",
    aboutLead1:
      "Resumora is a premium resume and career brand studio helping professionals secure stronger interviews and compensation outcomes in global markets.",
    aboutLead2:
      "Our delivery team includes senior resume strategists, recruiters, LinkedIn specialists, and interview coaches.",
    loginTitle: "Login",
    loginSubtitle: "Access your Resumora workspace and engagement-aware analytics.",
    loginEmail: "Email",
    loginPassword: "Password",
    loginSubmit: "Continue",
    loginSignedIn: "Signed in successfully.",
    errInvalidCredentials: "Invalid email or password.",
    errLoginGeneric: "Login failed.",
    forgotPasswordTitle: "Reset password",
    forgotPasswordSubtitle: "We will send a verification code by email and optional SMS.",
    forgotPasswordEmail: "Account email",
    forgotPasswordPhone: "Mobile (optional, for SMS code)",
    forgotPasswordChannelEmail: "Email code",
    forgotPasswordChannelSms: "SMS code",
    forgotPasswordChannelBoth: "Email + SMS",
    forgotPasswordSubmit: "Send verification code",
    forgotPasswordSent: "If an account exists, a verification code was sent.",
    forgotPasswordDeliveryFailed: "Message delivery failed. Please retry in a moment.",
    forgotPasswordRateLimited: "Too many attempts. Please wait before trying again.",
    resetPasswordTitle: "Choose a new password",
    resetPasswordSubtitle: "Enter the verification code and your new password.",
    resetPasswordCode: "Verification code",
    resetPasswordNew: "New password",
    resetPasswordConfirm: "Confirm password",
    resetPasswordSubmit: "Update password",
    resetPasswordSuccess: "Password updated. You are signed in.",
    resetPasswordMismatch: "Passwords do not match.",
    resetPasswordInvalidCode: "Invalid or expired code.",
    resetPasswordTooShort: "Password must be at least 8 characters.",
    loginForgotLink: "Forgot password?",
    registerTitle: "Register",
    registerSubtitle: "Create an account to sync likes, saves, and follows across sessions.",
    registerName: "Full name",
    registerSubmit: "Create account",
    registerCreated: "Account created.",
    registerPlanEyebrow: "Checkout path",
    registerPlanLead: "You're creating an account to continue with this tier:",
    registerPlanPriceNote: "one-time studio delivery · taxes where applicable",
    registerPlanAfterAccount: "After your account is created, you'll return to pricing to launch secure Stripe checkout for this plan.",
    registerPlanViewPricing: "Review all plans on pricing",
    errEmailInUse: "That email is already registered.",
    errRegisterGeneric: "Registration failed.",
    dashboardTitle: "Engagement analytics",
    dashboardLead:
      "Aggregates feed BossMind event logs when Neon is configured. Signed-in state:",
    dashboardFollowers: "Followers:",
    dashboardProfiles: "Registered profiles:",
    dashboardNeon: "Neon engagement store:",
    dashboardNeonOffline: "offline",
    dashboardNeonOnline: "online",
    dashboardBackEngagement: "Back to engagement",
    dashboardSignOut: "Sign out",
    dashboardAnonymous: "anonymous visitor",
    dashboardSession: "session",
    cancelTitle: "Payment cancelled",
    cancelLead: "No charges were made.",
    cancelBodyPrefix: "You can return to",
    cancelBodySuffix: "and choose another plan.",
    successVerifying: "Verifying payment",
    successWait: "Please wait while we confirm your payment session.",
    successPaymentTitle: "Payment successful",
    successThanks: "Thank you for choosing Resumora.",
    successVerified: "Your payment has been verified successfully.",
    successPrivateFeedbackHint:
      "Share private feedback (ratings, delivery notes) only through secure channels — never as a public dislike.",
    successPrivateFeedbackCta: "Email private feedback",
    successInvalidTitle: "Invalid session",
    successInvalidLead: "We could not verify this payment session.",
    successErrorTitle: "Verification error",
    successErrorLead: "Something went wrong while verifying your payment.",
    heroSecureUpload: "Secure upload",
    homeEyebrow: "Executive career studio",
    homeHeadline: "Elite career positioning for executives and high-value talent.",
    homeLead: "Strategist-led résumés, ATS-ready delivery, and secure bilingual checkout.",
    trustAuthorityLabel: "Studio",
    trustAuthorityBadges: ["ATS-ready", "Secure Stripe", "EN / FR"],
    essentialAdvancedTagline: "Executive upgrade lane · interview-ready",
    executiveFlowLabel: "Studio flow",
    executiveFlowSteps: [
      { title: "Position", line: "Executive narrative and hierarchy." },
      { title: "Refine", line: "Strategist review and ATS-safe exports." },
      { title: "Deliver", line: "Secure studio and bilingual when needed." },
    ],
    pricingViewAllFeatures: "View full deliverables",
    pricingHideFeatures: "Show less",
    essentialAdvancedWhatsIncluded: "What's included — interview studio",
    essentialAdvancedWhatsIncludedHide: "Hide interview studio details",
    essentialAdvancedStudioPreview: "Preview interview studio",
    essentialAdvancedAutoVideos: "3 auto-generated training videos · EN/FR",
    eaStudioTitle: "Essential Advanced Interview Studio",
    eaStudioLead: "Premium interview preparation unlocked with your Essential Advanced plan.",
    eaStudioLoading: "Loading your interview studio…",
    eaStudioLockedTitle: "Interview studio locked",
    eaStudioLockedLead: "Activate Essential Advanced ($110) to access videos, simulations, Q&A, and downloads.",
    eaStudioLockedCta: "View Essential Advanced plan",
    eaStudioAuthTitle: "Sign in to your studio",
    eaStudioAuthLead: "Create a free account to access purchased interview materials and track progress.",
    eaStudioAuthCta: "Register & unlock studio",
    eaStudioError: "Could not load your studio. Try again.",
    eaStudioRetry: "Retry",
    eaStudioProgressLabel: "Preparation progress",
    eaStudioNavLabel: "Interview preparation sections",
    eaStudioTabVideos: "Training videos",
    eaStudioTabSimulations: "Simulations",
    eaStudioTabQa: "Q&A bank",
    eaStudioTabTips: "Success tips",
    eaStudioTabExecutive: "Executive prep",
    eaStudioTabDownloads: "Downloads",
    eaStudioMarkComplete: "Mark complete",
    eaVideoLoading: "Loading secure video…",
    eaVideoError: "Video could not load. Retry or use the alternate stream.",
    eaVideoFallback: "Alternate stream",
    eaVideoFallbackActive: "Playing alternate stream (French locale).",
    eaStudioQaCount: "interview questions with model answers",
    eaDurationMin: "min",
    eaStudioLangLabel: "Language",
    successEaStudioCta: "Open Interview Studio",
    successEaStudioHint: "Your Essential Advanced interview materials are ready in your private studio.",
    successClientHubCta: "Open Client Hub",
    successClientHubHint: "Your premium deliverables and studio access are ready.",
    clientHubTitle: "Resumora Client Hub",
    clientHubLead: "Your purchased plans, downloads, and studio tools in one place.",
    clientHubLoading: "Loading your client hub…",
    clientHubAuthTitle: "Sign in to your client hub",
    clientHubAuthLead: "Use the email from checkout to access purchased deliverables.",
    clientHubAuthCta: "Sign in",
    clientHubEmptyTitle: "No active plans yet",
    clientHubEmptyLead: "Complete checkout on a plan to unlock your client hub.",
    clientHubEmptyCta: "Choose a Plan",
    clientHubError: "Could not load client hub.",
    clientHubRetry: "Retry",
    clientHubOpenStudio: "Open studio",
    clientHubDownloadWelcome: "Download welcome guide",
    homeMetaTitle: "Resumora | Executive resume studio — ATS-safe, bilingual EN/FR",
    homeMetaDescription:
      "Executive resumes, LinkedIn, and interview prep for leaders. ATS-safe collateral, bilingual EN/FR delivery, concierge cadence. Secure intake at resumora.net.",
    homeStripTitle: "Ready when you are",
    homeStripSubtitle: "Four studio lanes · secure Stripe · strategist-led delivery.",
    homeStripPrimary: "View pricing",
    homeStripSecondary: "Concierge chat",
    pricingOneTimeNote: "/month",
    pricingFreeEditsBadge: "Free edits included",
    checkoutSummaryTitle: "Checkout summary",
    checkoutSummaryEdits: "Included revisions",
    successFreeEditsLine: "Your plan includes structured revision credits:",
    clientHubFreeEdits: "Revision credits",
    registerFreeEditsNote: "Includes revision credits with your plan",
    chatSendError: "Could not send. Email support@resumora.net directly.",
    ctaPricingUrl: "resumora.net/pricing",
    engagementMetricFollowers: "Followers",
    engagementMetricRegistrations: "Registered clients",
    engagementMetricNeon: "Neon sync",
    engagementMetricShares: "Share signals (logged)",
    engagementSyncedShort: "Engagement snapshot",
    engagementShareCta: "Share lane",
    engagementShareText: "Resumora studio lane — executive collateral and ATS-safe delivery.",
    engagementNeonLive: "Live",
    engagementAnalyticsLink: "Analytics dashboard",
    engagementEmptySignals: "Awaiting first signals",
    engagementSubscribeShort: "Updates",
    svcQuoteCustomize: "Configure",
    svcQuoteHide: "Close",
    svcQuoteSummary: "Order summary",
    svcQuoteEstimated: "Scope estimate",
    svcQuoteStripeNote:
      "Secured Stripe checkout charges your selected tier rate. Scope details are relayed to your strategist via order metadata.",
    svcQuoteContinue: "Continue to pricing & checkout",
    svcQuoteTier: "Tier",
    svcQuotePages: "Pages",
    svcQuoteResumeType: "Résumé type",
    svcQuoteLanguage: "Language delivery",
    svcQuoteAddons: "Add-ons",
    svcQuoteDelivery: "Delivery",
    svcTierBasic: "Basic",
    svcTierProfessional: "Professional",
    svcTierElite: "Elite",
    svcTierEssentialAdvanced: "Essential Advanced",
    pricingCompareInterviewPack: "Interview prep bundle",
    pricingCompareSimulations: "Live-style interview simulations",
    pricingCompareTrainingVideos: "Professional training videos",
    pricingCompareQaBank: "Recruiter Q&A library",
    pricingCompareSuccessTips: "Success tips playbook",
    svcPages1: "1 page",
    svcPages2: "2 pages",
    svcPages3: "3 pages",
    svcPages4: "4 pages",
    svcResumeChronological: "Chronological",
    svcResumeHybrid: "Hybrid",
    svcResumeExecutive: "Executive condensed",
    svcLangEn: "English only",
    svcLangFr: "French only",
    svcLangBilingual: "EN + FR pair",
    svcAddonLetter: "Strategic letter",
    svcAddonLinkedin: "LinkedIn sprint",
    svcAddonInterview: "Interview pack",
    svcDeliveryStandard: "Standard cadence",
    svcDeliveryExpedited: "Expedited",
    svcDeliveryRush: "Concierge rush",
    svcQuoteLineTierBase: "Plan base",
    svcQuoteLineExtraPages: "Extra pages",
    svcQuoteLineResumeType: "Format preference",
    svcQuoteLineLanguage: "Localisation uplift",
    svcQuoteLineDelivery: "Accelerated delivery",
    svcQuoteAddon_strategicLetter: "Strategic letter",
    svcQuoteAddon_linkedinSprint: "LinkedIn sprint",
    svcQuoteAddon_interviewPack: "Interview rehearsal",
    pricingFromConfigurator: "From your configuration",
    pricingConfiguratorClear: "Clear saved scope",
  },
  fr: {
    navHome: "Accueil",
    navTrust: "Confiance",
    navServices: "Services",
    navPricing: "Tarifs",
    navCapabilities: "Capacités",
    navDelivery: "Livraison",
    navEngagement: "Engagement",
    navTestimonials: "Récits",
    navContact: "Contact",
    navLogin: "Connexion",
    navRegister: "Inscription",
    openMenu: "Ouvrir le menu",
    closeMenu: "Fermer le menu",
    uploadEyebrow: "Réception confidentielle",
    uploadTitle: "Téléversement exécutif sécurisé",
    uploadText: "Remise chiffrée pour revue stratège—alignement ATS et clarté de narration.",
    uploadButton: "Téléverser le document",
    uploadSuccess: "Téléversement terminé avec succès.",
    uploadError: "Échec du téléversement. Veuillez réessayer.",
    uploadHint: "PDF, DOC, DOCX · Documents de longueur exécutive.",
    uploadDropTitle: "Déposez votre CV ici",
    uploadDropHint: "ou cliquez pour parcourir · traitement confidentiel",
    uploadConfidentialLine: "Traitement exécutif confidentiel · chiffrement en transit",
    servicesTitle: "Capacités structurées",
    servicesSubtitle:
      "Modules distincts à composer—ancrés sur le comportement recruteur et les ATS du marché.",
    serviceAction: "Poursuivre",
    serviceCategory: "Périmètre",
    capabilitiesTitle: "Capacités entreprise",
    capabilitiesSubtitle: "Modules niveau institutionnel alignés sur attentes de comités de recrutement.",
    servicesPageTitle: "Services & réception",
    servicesPageSubtitle: "Commencez par un téléversement sécurisé ou explorez chaque volet.",
    pricingTitle: "Plans d'upgrade de carrière professionnelle",
    pricingSubtitle:
      "Choisissez le bon niveau d'upgrade exécutif pour CV, ATS, LinkedIn et préparation aux entretiens.",
    popular: "Le plus choisi",
    selectPlan: "Sélectionner le plan",
    ctaSelectBasic: "Démarrer Basic",
    ctaSelectProfessional: "Choisir Professionnel",
    ctaSelectElite: "Lancer Élite concierge",
    ctaSelectEssentialAdvanced: "Activer Essential Avancé",
    processing: "Traitement…",
    deliveryProtocolsTitle: "Protocoles de livraison",
    deliveryProtocolsSubtitle:
      "Jalons gouvernés—de l’intake chiffré à l’export compatible ATS, reproductibles pour audit et montée en charge.",
    engagementTitle: "Engagement en direct",
    engagementSubtitle:
      "Indicateurs issus d’interactions stockées sur Neon—pas de faux compteurs. Suivez Resumora pour la cadence produit.",
    engagementFollow: "Suivre Resumora",
    engagementFollowing: "Abonné",
    engagementLike: "J’aime",
    engagementSave: "Enregistrer",
    engagementRequest: "Signal d’intention",
    engagementTrending: "Services tendance",
    engagementMostLiked: "Plus aimés",
    engagementMostSaved: "Plus sauvegardés",
    engagementMostRequested: "Plus demandés",
    engagementDisabled: "L’engagement nécessite Neon (base de données).",
    testimonialsTitle: "Résultats clients",
    testimonialsSubtitle:
      "Retours d’exécutifs et profils seniors après missions de repositionnement.",
    trustTitle: "Confiance, en synthèse",
    trustSubtitle:
      "Intake chiffré, livraison encadrée et checkout explicable à la procurement en une phrase.",
    trustSecureDelivery:
      "Intake chiffré, artefacts encadrés, signaux publics positifs—checkout sans artifices.",
    trustStrip:
      "Greenhouse · Lever · Workday · PDF/DOC compatibles ATS · Recrutement global · Livrables EN/FR",
    engagementStripTitle: "Momentum studio (semaine type)",
    engagementHeatLabel: "Signal de rythme de livraison",
    engagementSessionsLabel: "Bande d’intake",
    engagementApprovalLabel: "Ressenti validation parties prenantes",
    engagementRecommendLabel: "Recommandation (bande sondage)",
    engagementSignalsDisclaimer:
      "Bande illustrative pour une semaine studio premium—pas un compteur d’utilisateurs simultanés. Les valeurs évoluent lentement pour refléter une variance opérationnelle normale.",
    engagementDisclaimerAnalytics:
      "Signaux produit agrégés et anonymisés (j’aime, enregistrements, intentions et vues de pages grossières)—pas de visiteurs simultanés. Lissage pour éviter les pics horaires.",
    engagementDisclaimerBlended:
      "Mélange de signaux réels légers avec des bandes studio lorsque l’échantillon reste modeste—pas un compteur en direct.",
    engagementPopularLabel: "Voie populaire",
    engagementTrendingChip: "Forte demande",
    engagementVerifiedReview: "Retour client vérifié",
    engagementSessionsLabelSignals: "Bande de signaux (7 j.)",
    engagementMicroCtaStories: "Récits clients",
    engagementMicroCtaPricing: "Comparer les paliers",
    engagementRecentlySelected: "Cadence de sélection",
    engagementSatisfactionTrust:
      "Les signaux de satisfaction restent positifs dans les vues publiques—pas de compteurs de désaccord.",
    badgeBestValue: "Meilleur rapport valeur",
    badgeBalanced: "Équilibré",
    badgeMostPopular: "Le plus sélectionné",
    pricingTrustSecureLine: "Stripe sécurisé · intake chiffré · supports jamais revendus.",
    pricingWorkflowTrustLine:
      "Après paiement, une note de routage concierge arrive dans le SLA indiqué sur votre reçu.",
    pricingCompareHint:
      "Chaque palier livre des livrables compatibles ATS. Élite ajoute profondeur concierge, relance LinkedIn et assets de répétition lorsque le mandat est visible et urgent.",
    pricingCompareTitle: "Profondeur studio en un coup d’œil",
    pricingCompareLead: "Voyez ce qui change entre les voies—sans tableau procurement.",
    pricingCompareExpand: "Voir la comparaison complète",
    pricingCompareCollapse: "Réduire le détail",
    pricingEliteHighlight:
      "Élite — livraison concierge premium pour un positionnement directionnel.",
    pricingEssentialAdvancedHighlight:
      "Essential Advanced (110 $) — quatrième palier (à droite) : CV prêt ATS avec mise en forme, mots-clés, lettre, délai accéléré et révisions limitées.",
    badgeInterviewStudio: "Studio entretien",
    badgeEssentialAdvanced: "Studio avancé",
    footerTagline:
      "Resumora produit des dossiers carrière de niveau institutionnel pour les leaders qui refusent le générique.",
    footerColProduct: "Produit",
    footerColCompany: "Entreprise",
    footerColLegal: "Juridique",
    footerAbout: "À propos",
    footerServices: "Services",
    footerPricing: "Tarifs",
    footerUpload: "Téléversement",
    footerTrust: "Indicateurs",
    footerCapabilities: "Capacités",
    footerDelivery: "Livraison",
    footerEngagement: "Engagement",
    footerStories: "Récits",
    footerTerms: "Conditions",
    footerPrivacy: "Confidentialité",
    footerSupport: "Support",
    footerContact: "Contact",
    footerCopy: "© 2026 Resumora. Tous droits réservés.",
    installPwaTitle: "Installer Resumora pour un accès plus rapide",
    installPwaInstall: "Installer",
    installPwaDismiss: "Plus tard",
    navGroupOverview: "Vue d’ensemble",
    navGroupProduct: "Services & livraison",
    navGroupExperience: "Récits & engagement",
    navGroupSupport: "Entreprise & support",
    sidebarNavLabel: "Navigation studio",
    footerAboutLuxury:
      "Studio CV direction — dossiers compatibles ATS, livraison EN/FR, cadence concierge.",
    footerColReach: "Contact",
    footerEmail: "support@resumora.net",
    footerLiveChat: "Chat en direct",
    footerAutomated247: "Accusé automatisé 24h/24 à réception",
    footerRefund: "Politique de remboursement",
    footerSystemPolicy: "Politique système & plateforme",
    footerSocial: "Réseaux",
    footerSocialPlaceholder: "Configurez les URLs NEXT_PUBLIC_SOCIAL_* pour les liens.",
    footerDockSocial: "Canaux officiels",
    footerDockEngage: "Confiance & signaux",
    footerEngageShare: "Partager",
    footerEngageRegister: "Inscription",
    footerPricingCta: "Comparer les paliers",
    footerToolbarAria: "Actions rapides Resumora",
    footerShareCopied: "Lien copié dans le presse-papiers.",
    footerShareFail: "Partage impossible. Copiez resumora.net manuellement.",
    footerEngageBarLead:
      "Paiement sécurisé Stripe · bilingue EN/FR · livraison concierge — signaux publics positifs uniquement.",
    footerTrustChipPopular: "Le plus sélectionné · profondeur Professionnel",
    footerTrustChipRecent: "Cadence de sélection · voies Professionnel & Élite",
    footerTrustChipElite: "Meilleur rapport · voie Élite studio",
    footerTrustChipSecure: "Intake chiffré · conservation encadrée",
    footerTrustChipAi: "Flux assisté par IA · contrôle éditorial humain",
    footerTrendingPrefix: "Tendance",
    footerLiveSignals: "Signaux produit en direct",
    footerConfigureNeon: "Connectez Neon pour les agrégats d’engagement",
    freeTestMetaTitle: "Revue gratuite",
    freeTestTitle: "Commencer la revue gratuite",
    freeTestLead:
      "Choisissez votre offre, la langue et le périmètre—aperçu seulement. Aucun paiement. La livraison complète nécessite un palier payant.",
    freeTestEmail: "E-mail professionnel",
    freeTestService: "Service",
    freeTestLang: "Langue préférée",
    freeTestPages: "Pages",
    freeTestNotes: "Objectif ou cible de rôle (facultatif)",
    freeTestUpload: "Joindre CV (PDF/DOC/DOCX)",
    freeTestOptional: "Facultatif",
    freeTestSubmit: "Envoyer la demande de revue",
    freeTestSuccess:
      "Reçu. Notre équipe répondra avec des repères d’aperçu—les livrables finaux passent par un plan payant.",
    freeTestLimit: "Un aperçu gratuit par e-mail.",
    freeTestDisclaimer:
      "Cette revue gratuite est une demande d’aperçu uniquement. Pas de paiement Stripe et ce n’est pas une livraison complète.",
    freeTestNeonError: "Base de données indisponible—réessayez après configuration Neon.",
    freeTestDuplicate: "Cet e-mail a déjà utilisé sa revue gratuite.",
    freeTestErrorGeneric: "Une erreur s’est produite. Écrivez à support@resumora.net si cela continue.",
    freeTestStartCta: "Commencer la revue gratuite",
    contactPageTitle: "Contact",
    contactMetaDescription: "Contact support Resumora — disponibilité 24h/24 et chat sécurisé.",
    contactHours247: "Disponibilité support : 24h/24, 7j/7.",
    contactAutoConfirm:
      "Configurez votre serveur mail pour qu’un accusé automatisé soit envoyé à chaque message vers support@resumora.net.",
    contactChatCta: "Ouvrir le chat sécurisé",
    langSwitcherAria: "Langue du site",
    langEnglish: "English",
    langFrench: "Français",
    minimalHomeAria: "Accueil Resumora",
    backHome: "Retour à l’accueil",
    returnHome: "Retour à l’accueil",
    navHomeShort: "Accueil",
    seoSolutionsEyebrow: "SEO · Solutions",
    heroSecureUploadShort: "Téléversement",
    pricingQuestionsTitle: "Questions avant paiement ?",
    pricingQuestionsSubtitle: "Routage concierge pour voies entreprise.",
    aboutTitle: "À propos de Resumora",
    aboutLead1:
      "Resumora est un studio premium de CV et de marque carrière qui aide les professionnels à obtenir de meilleurs entretiens et des résultats de rémunération sur les marchés mondiaux.",
    aboutLead2:
      "Notre équipe de livraison réunit des stratèges CV seniors, des recruteurs, des spécialistes LinkedIn et des coachs entretien.",
    loginTitle: "Connexion",
    loginSubtitle: "Accédez à votre espace Resumora et aux analyses d’engagement.",
    loginEmail: "E-mail",
    loginPassword: "Mot de passe",
    loginSubmit: "Continuer",
    loginSignedIn: "Connexion réussie.",
    errInvalidCredentials: "E-mail ou mot de passe invalide.",
    errLoginGeneric: "Échec de la connexion.",
    forgotPasswordTitle: "Réinitialiser le mot de passe",
    forgotPasswordSubtitle: "Nous enverrons un code de vérification par e-mail et SMS optionnel.",
    forgotPasswordEmail: "E-mail du compte",
    forgotPasswordPhone: "Mobile (optionnel, pour code SMS)",
    forgotPasswordChannelEmail: "Code par e-mail",
    forgotPasswordChannelSms: "Code par SMS",
    forgotPasswordChannelBoth: "E-mail + SMS",
    forgotPasswordSubmit: "Envoyer le code",
    forgotPasswordSent: "Si un compte existe, un code de vérification a été envoyé.",
    forgotPasswordDeliveryFailed: "Échec d’envoi. Réessayez dans un instant.",
    forgotPasswordRateLimited: "Trop de tentatives. Veuillez patienter.",
    resetPasswordTitle: "Nouveau mot de passe",
    resetPasswordSubtitle: "Saisissez le code de vérification et votre nouveau mot de passe.",
    resetPasswordCode: "Code de vérification",
    resetPasswordNew: "Nouveau mot de passe",
    resetPasswordConfirm: "Confirmer le mot de passe",
    resetPasswordSubmit: "Mettre à jour",
    resetPasswordSuccess: "Mot de passe mis à jour. Vous êtes connecté.",
    resetPasswordMismatch: "Les mots de passe ne correspondent pas.",
    resetPasswordInvalidCode: "Code invalide ou expiré.",
    resetPasswordTooShort: "Le mot de passe doit contenir au moins 8 caractères.",
    loginForgotLink: "Mot de passe oublié ?",
    registerTitle: "Inscription",
    registerSubtitle:
      "Créez un compte pour synchroniser vos interactions (j’aime, sauvegardes, suivis) entre sessions.",
    registerName: "Nom complet",
    registerSubmit: "Créer le compte",
    registerCreated: "Compte créé.",
    registerPlanEyebrow: "Parcours paiement",
    registerPlanLead: "Vous créez un compte pour poursuivre avec ce palier :",
    registerPlanPriceNote: "prestation studio ponctuelle · taxes selon juridiction",
    registerPlanAfterAccount:
      "Après la création du compte, vous reviendrez sur les tarifs pour lancer le paiement Stripe sécurisé pour ce plan.",
    registerPlanViewPricing: "Voir tous les plans",
    errEmailInUse: "Cette adresse e-mail est déjà enregistrée.",
    errRegisterGeneric: "Échec de l’inscription.",
    dashboardTitle: "Analytique d’engagement",
    dashboardLead:
      "Les agrégats alimentent les journaux d’événements BossMind lorsque Neon est configuré. État connecté :",
    dashboardFollowers: "Abonnés :",
    dashboardProfiles: "Profils enregistrés :",
    dashboardNeon: "Stockage engagement Neon :",
    dashboardNeonOffline: "hors ligne",
    dashboardNeonOnline: "en ligne",
    dashboardBackEngagement: "Retour à l’engagement",
    dashboardSignOut: "Se déconnecter",
    dashboardAnonymous: "visiteur anonyme",
    dashboardSession: "session",
    cancelTitle: "Paiement annulé",
    cancelLead: "Aucun débit n’a été effectué.",
    cancelBodyPrefix: "Vous pouvez revenir sur",
    cancelBodySuffix: "et choisir un autre plan.",
    successVerifying: "Vérification du paiement",
    successWait: "Veuillez patienter pendant que nous confirmons votre session de paiement.",
    successPaymentTitle: "Paiement réussi",
    successThanks: "Merci d’avoir choisi Resumora.",
    successVerified: "Votre paiement a été vérifié avec succès.",
    successPrivateFeedbackHint:
      "Pour un retour privé (notes, livraison), utilisez uniquement les canaux sécurisés — jamais comme « dislike » public.",
    successPrivateFeedbackCta: "Envoyer un retour privé par e-mail",
    successInvalidTitle: "Session invalide",
    successInvalidLead: "Nous n’avons pas pu vérifier cette session de paiement.",
    successErrorTitle: "Erreur de vérification",
    successErrorLead: "Un problème est survenu lors de la vérification du paiement.",
    heroSecureUpload: "Téléversement sécurisé",
    homeEyebrow: "Studio carrière exécutif",
    homeHeadline: "Positionnement d'élite pour cadres et talents à haute valeur.",
    homeLead: "CV par stratège, livraison ATS et paiement bilingue sécurisé.",
    trustAuthorityLabel: "Studio",
    trustAuthorityBadges: ["Compatible ATS", "Stripe sécurisé", "EN / FR"],
    essentialAdvancedTagline: "Voie upgrade exécutive · prêt entretien",
    executiveFlowLabel: "Parcours studio",
    executiveFlowSteps: [
      { title: "Position", line: "Narratif exécutif et hiérarchie." },
      { title: "Affinage", line: "Revue stratège et exports ATS." },
      { title: "Livraison", line: "Studio sécurisé et bilingue au besoin." },
    ],
    pricingViewAllFeatures: "Voir tous les livrables",
    pricingHideFeatures: "Réduire",
    essentialAdvancedWhatsIncluded: "Inclus — studio entretien",
    essentialAdvancedWhatsIncludedHide: "Masquer le studio entretien",
    essentialAdvancedStudioPreview: "Aperçu du studio entretien",
    essentialAdvancedAutoVideos: "3 vidéos auto-générées · EN/FR",
    eaStudioTitle: "Studio entretien Essential Advanced",
    eaStudioLead: "Préparation entretien premium incluse avec votre plan Essential Advanced.",
    eaStudioLoading: "Chargement du studio…",
    eaStudioLockedTitle: "Studio verrouillé",
    eaStudioLockedLead: "Activez Essential Advanced (110 $ US) pour vidéos, simulations, Q&R et téléchargements.",
    eaStudioLockedCta: "Voir le plan Essential Advanced",
    eaStudioAuthTitle: "Connectez-vous au studio",
    eaStudioAuthLead: "Créez un compte pour accéder aux contenus achetés et suivre votre progression.",
    eaStudioAuthCta: "S'inscrire et déverrouiller",
    eaStudioError: "Impossible de charger le studio.",
    eaStudioRetry: "Réessayer",
    eaStudioProgressLabel: "Progression préparation",
    eaStudioNavLabel: "Sections préparation entretien",
    eaStudioTabVideos: "Vidéos",
    eaStudioTabSimulations: "Simulations",
    eaStudioTabQa: "Banque Q&R",
    eaStudioTabTips: "Conseils",
    eaStudioTabExecutive: "Prep exécutive",
    eaStudioTabDownloads: "Téléchargements",
    eaStudioMarkComplete: "Marquer terminé",
    eaVideoLoading: "Chargement de la vidéo sécurisée…",
    eaVideoError: "Impossible de charger la vidéo. Réessayez ou utilisez le flux alternatif.",
    eaVideoFallback: "Flux alternatif",
    eaVideoFallbackActive: "Lecture du flux alternatif (interface française).",
    eaStudioQaCount: "questions avec réponses modèles",
    eaDurationMin: "min",
    eaStudioLangLabel: "Langue",
    successEaStudioCta: "Ouvrir le studio entretien",
    successEaStudioHint: "Vos contenus Essential Advanced sont prêts dans votre studio privé.",
    successClientHubCta: "Ouvrir l'espace client",
    successClientHubHint: "Vos livrables premium et studios sont prêts.",
    clientHubTitle: "Espace client Resumora",
    clientHubLead: "Vos forfaits, téléchargements et studios en un seul endroit.",
    clientHubLoading: "Chargement de l'espace client…",
    clientHubAuthTitle: "Connectez-vous",
    clientHubAuthLead: "Utilisez l'e-mail du paiement pour accéder aux livrables.",
    clientHubAuthCta: "Connexion",
    clientHubEmptyTitle: "Aucun forfait actif",
    clientHubEmptyLead: "Finalisez un paiement pour déverrouiller l'espace client.",
    clientHubEmptyCta: "Choisir un forfait",
    clientHubError: "Impossible de charger l'espace client.",
    clientHubRetry: "Réessayer",
    clientHubOpenStudio: "Ouvrir le studio",
    clientHubDownloadWelcome: "Télécharger le guide",
    homeMetaTitle: "Resumora | Studio CV direction — compatible ATS, bilingue EN/FR",
    homeMetaDescription:
      "CV direction, LinkedIn et préparation entretien pour cadres. Livrables compatibles ATS, livraison bilingue EN/FR, cadence concierge. Intake sécurisé sur resumora.net.",
    homeStripTitle: "Prêt quand vous l’êtes",
    homeStripSubtitle: "Quatre voies studio · Stripe sécurisé · livraison par stratège.",
    homeStripPrimary: "Voir les tarifs",
    homeStripSecondary: "Chat concierge",
    pricingOneTimeNote: "/mois",
    pricingFreeEditsBadge: "Révisions gratuites incluses",
    checkoutSummaryTitle: "Récapitulatif",
    checkoutSummaryEdits: "Révisions incluses",
    successFreeEditsLine: "Votre forfait inclut des crédits de révision :",
    clientHubFreeEdits: "Crédits révision",
    registerFreeEditsNote: "Crédits de révision inclus avec votre forfait",
    chatSendError: "Envoi impossible. Écrivez à support@resumora.net.",
    ctaPricingUrl: "resumora.net/pricing",
    engagementMetricFollowers: "Abonnés",
    engagementMetricRegistrations: "Clients inscrits",
    engagementMetricNeon: "Sync Neon",
    engagementMetricShares: "Signaux de partage (journalisés)",
    engagementSyncedShort: "Instantané engagement",
    engagementShareCta: "Partager la voie",
    engagementShareText:
      "Studio Resumora — dossiers direction et livrables compatibles ATS.",
    engagementNeonLive: "Actif",
    engagementAnalyticsLink: "Tableau analytics",
    engagementEmptySignals: "En attente de signaux",
    engagementSubscribeShort: "Flux",
    svcQuoteCustomize: "Configurer",
    svcQuoteHide: "Fermer",
    svcQuoteSummary: "Récapitulatif",
    svcQuoteEstimated: "Estimation de périmètre",
    svcQuoteStripeNote:
      "Le paiement Stripe sécurisé facture le palier choisi. Le détail du périmètre est transmis au stratège via les métadonnées de commande.",
    svcQuoteContinue: "Poursuivre vers tarifs & paiement",
    svcQuoteTier: "Palier",
    svcQuotePages: "Pages",
    svcQuoteResumeType: "Type de CV",
    svcQuoteLanguage: "Livraison linguistique",
    svcQuoteAddons: "Options",
    svcQuoteDelivery: "Livraison",
    svcTierBasic: "Basic",
    svcTierProfessional: "Professionnel",
    svcTierElite: "Élite",
    svcTierEssentialAdvanced: "Essential Avancé",
    pricingCompareInterviewPack: "Forfait préparation entretien",
    pricingCompareSimulations: "Simulations d'entretien réalistes",
    pricingCompareTrainingVideos: "Vidéos de formation pro",
    pricingCompareQaBank: "Banque Q&R recruteur",
    pricingCompareSuccessTips: "Playbook conseils succès",
    svcPages1: "1 page",
    svcPages2: "2 pages",
    svcPages3: "3 pages",
    svcPages4: "4 pages",
    svcResumeChronological: "Chronologique",
    svcResumeHybrid: "Hybride",
    svcResumeExecutive: "Exécutif condensé",
    svcLangEn: "Anglais seul",
    svcLangFr: "Français seul",
    svcLangBilingual: "Paire EN + FR",
    svcAddonLetter: "Lettre stratégique",
    svcAddonLinkedin: "Sprint LinkedIn",
    svcAddonInterview: "Pack entretien",
    svcDeliveryStandard: "Cadence standard",
    svcDeliveryExpedited: "Accéléré",
    svcDeliveryRush: "Rush concierge",
    svcQuoteLineTierBase: "Base du palier",
    svcQuoteLineExtraPages: "Pages supplémentaires",
    svcQuoteLineResumeType: "Préférence de format",
    svcQuoteLineLanguage: "Supplément bilingue",
    svcQuoteLineDelivery: "Livraison accélérée",
    svcQuoteAddon_strategicLetter: "Lettre stratégique",
    svcQuoteAddon_linkedinSprint: "Sprint LinkedIn",
    svcQuoteAddon_interviewPack: "Répétitions entretien",
    pricingFromConfigurator: "Depuis votre configuration",
    pricingConfiguratorClear: "Effacer le périmètre enregistré",
  },
};

export function processSteps(lang) {
  return lang === "en"
    ? [
        {
          title: "Secure upload",
          detail: "Encrypted intake, role classification, and scope lock.",
          step: "01",
          Icon: FileText,
        },
        {
          title: "ATS + human audit",
          detail: "Parser logic crossed with recruiter skim heuristics.",
          step: "02",
          Icon: Shield,
        },
        {
          title: "Executive rewrite",
          detail: "Structure, KPI density, and leadership tone rebuilt.",
          step: "03",
          Icon: ClipboardPenLine,
        },
        {
          title: "Polish & release",
          detail: "ATS-safe layout validation and final artefact handoff.",
          step: "04",
          Icon: CheckCircle2,
        },
      ]
    : [
        {
          title: "Téléversement sécurisé",
          detail: "Réception chiffrée, qualification du poste et périmètre figé.",
          step: "01",
          Icon: FileText,
        },
        {
          title: "Audit ATS + humain",
          detail: "Parseur croisé avec heuristiques de lecture recruteur.",
          step: "02",
          Icon: Shield,
        },
        {
          title: "Réécriture exécutive",
          detail: "Structure, densité KPI et ton de direction reconstruits.",
          step: "03",
          Icon: ClipboardPenLine,
        },
        {
          title: "Finitions & remise",
          detail: "Validation mise en page ATS-safe et livraison finale.",
          step: "04",
          Icon: CheckCircle2,
        },
      ];
}

export function testimonialsList(lang) {
  return lang === "en"
    ? [
        {
          quote:
            "They reframed my mandate without diluting my voice. Quality callbacks inside two weeks.",
          author: "Morgan L.",
          role: "Director of Product, Fintech",
        },
        {
          quote: "Finally, ATS pass-through matched how strong my operating record actually reads.",
          author: "James K.",
          role: "VP Engineering",
        },
        {
          quote: "Bilingual EN/FR packs unlocked Paris and Montréal searches with one coherent narrative.",
          author: "Amélie R.",
          role: "Strategy Lead",
        },
      ]
    : [
        {
          quote:
            "Ils ont recadré mon mandat sans diluer ma voix. Retours qualité en moins de deux semaines.",
          author: "Morgan L.",
          role: "Directrice produit, fintech",
        },
        {
          quote: "Enfin un passage ATS à la hauteur de mon historique opérationnel réel.",
          author: "James K.",
          role: "VP ingénierie",
        },
        {
          quote: "Les livrables bilingues EN/FR ont débloqué Paris et Montréal avec une narration unique.",
          author: "Amélie R.",
          role: "Lead stratégie",
        },
      ];
}

export const SERVICE_LABELS = {
  en: {
    svc_ats: "ATS optimisation",
    svc_letter: "Strategic letter",
    svc_linkedin: "LinkedIn relaunch",
    svc_interview: "Interview prep",
    svc_tls: "Translation / TLS",
    svc_support: "Priority support",
  },
  fr: {
    svc_ats: "Optimisation ATS",
    svc_letter: "Lettre stratégique",
    svc_linkedin: "Relance LinkedIn",
    svc_interview: "Préparation entretien",
    svc_tls: "Traduction / TLS",
    svc_support: "Support prioritaire",
  },
};

export const servicesByLang = {
  en: [
    {
      resourceKey: "svc_ats",
      category: "Resume strategy",
      title: "ATS resume optimisation",
      description:
        "Full-spectrum rewrite with lexical precision, parser-safe layout, and section flow proven across major ATS vendors.",
      ctaHref: "/services#intake",
      ctaLabel: "Upload for review",
      Icon: FileText,
    },
    {
      resourceKey: "svc_letter",
      category: "Application assets",
      title: "Strategic cover letter",
      description:
        "Narratives tied to mandate, culture cues, and quantified proof so submissions feel bespoke at scale.",
      ctaHref: "/services#intake",
      ctaLabel: "Start with intake",
      Icon: PenLine,
    },
    {
      resourceKey: "svc_linkedin",
      category: "Personal brand",
      title: "LinkedIn repositioning",
      description:
        "Authority-forward headline, featured media, and discoverability calibrated to recruiter search norms.",
      ctaHref: "/pricing",
      ctaLabel: "Select tier",
      Icon: BriefcaseBusiness,
    },
    {
      resourceKey: "svc_interview",
      category: "Interview readiness",
      title: "Interview preparation",
      description:
        "Scenario drills and executive presence aligned to your reconstructed dossier—not generic scripts.",
      ctaHref: "/pricing",
      ctaLabel: "Book preparation",
      Icon: Mic2,
    },
    {
      resourceKey: "svc_tls",
      category: "Localisation",
      title: "Translation / TLS",
      description:
        "Native-grade EN/FR pairs with tonal harmonisation across resume, outreach, and follow-up artefacts.",
      ctaHref: "/capabilities",
      ctaLabel: "View capabilities",
      Icon: Languages,
    },
    {
      resourceKey: "svc_support",
      category: "Concierge",
      title: "Priority support",
      description:
        "Concierge pacing, explicit SLAs, and direct escalation whenever velocity is non-negotiable.",
      ctaHref: "/pricing",
      ctaLabel: "Upgrade tier",
      Icon: Headphones,
    },
  ],
  fr: [
    {
      resourceKey: "svc_ats",
      category: "Stratégie CV",
      title: "Optimisation CV ATS",
      description:
        "Réécriture complète, mise en page parseur-safe et enchaînement de sections éprouvé chez les grands ATS.",
      ctaHref: "/services#intake",
      ctaLabel: "Téléverser pour audit",
      Icon: FileText,
    },
    {
      resourceKey: "svc_letter",
      category: "Dossiers candidature",
      title: "Lettre stratégique",
      description:
        "Narratifs reliés au mandat, signaux culture et preuves chiffrées pour un rendu sur-mesure industriel.",
      ctaHref: "/services#intake",
      ctaLabel: "Par l’intake",
      Icon: PenLine,
    },
    {
      resourceKey: "svc_linkedin",
      category: "Marque personnelle",
      title: "Relance LinkedIn",
      description:
        "Titre d’autorité, médias vedettes et découvrabilité calibrées aux usages de recherche recruteur.",
      ctaHref: "/pricing",
      ctaLabel: "Choisir le palier",
      Icon: BriefcaseBusiness,
    },
    {
      resourceKey: "svc_interview",
      category: "Entretien",
      title: "Préparation entretien",
      description:
        "Drills situationnels et présence cadre synchronisés sur votre dossier reconstruit—pas de scripts génériques.",
      ctaHref: "/pricing",
      ctaLabel: "Réserver",
      Icon: Mic2,
    },
    {
      resourceKey: "svc_tls",
      category: "Localisation",
      title: "Traduction / TLS",
      description:
        "Paires EN/FR niveau native avec harmonisation sur tous les artefacts de poursuite.",
      ctaHref: "/capabilities",
      ctaLabel: "Voir les capacités",
      Icon: Languages,
    },
    {
      resourceKey: "svc_support",
      category: "Conciergerie",
      title: "Support prioritaire",
      description:
        "Rythme concierge, SLA explicites et remontée directe lorsque la vitesse est critique.",
      ctaHref: "/pricing",
      ctaLabel: "Monter de palier",
      Icon: Headphones,
    },
  ],
};

export const pricingPlans = [
  {
    id: "basic",
    freeEdits: 1,
    name: { en: "Basic", fr: "Basic" },
    price: `$${BASIC_PRICE_USD}`,
    env: "NEXT_PUBLIC_STRIPE_PRICE_BASIC",
    featured: false,
    badge: null,
    features: {
      en: [
        "1 Free Resume Edit",
        "AI-powered Suggestions",
        "Standard Templates",
        "Email Support (48h)",
      ],
      fr: [
        "1 révision CV gratuite",
        "Suggestions IA",
        "Modèles standard",
        "Support courriel (48 h)",
      ],
    },
  },
  {
    id: "professional",
    freeEdits: 3,
    name: { en: "Standard", fr: "Standard" },
    price: `$${PRO_PRICE_USD}`,
    env: "NEXT_PUBLIC_STRIPE_PRICE_PRO",
    featured: false,
    badge: "balanced",
    features: {
      en: [
        "3 Free Resume Edits",
        "Cover Letter Included",
        "Advanced ATS Optimization",
        "Priority Email Support",
      ],
      fr: [
        "3 révisions CV gratuites",
        "Lettre de motivation incluse",
        "Optimisation ATS avancée",
        "Support courriel prioritaire",
      ],
    },
  },
  {
    id: "elite",
    freeEdits: 0,
    name: { en: "Professional", fr: "Professionnel" },
    price: `$${ELITE_PRICE_USD}`,
    env: "NEXT_PUBLIC_STRIPE_PRICE_ELITE",
    featured: true,
    badge: "flagship",
    features: {
      en: [
        "Unlimited Resume Edits",
        "LinkedIn Profile Sync",
        "Interview Prep Assistant",
        "24/7 Chat Support",
      ],
      fr: [
        "Révisions CV illimitées",
        "Synchronisation profil LinkedIn",
        "Assistant préparation entretien",
        "Support chat 24/7",
      ],
    },
  },
  {
    id: "essential_advanced",
    freeEdits: 0,
    name: { en: "Enterprise", fr: "Entreprise" },
    price: `$${ESSENTIAL_ADVANCED_PRICE_USD}`,
    env: "NEXT_PUBLIC_STRIPE_PRICE_ESSENTIAL_ADVANCED",
    featured: false,
    badge: "advanced",
    features: {
      en: [
        "Everything in Professional",
        "Team Management (up to 5)",
        "Custom Branding & URL",
        "Dedicated Account Manager",
      ],
      fr: [
        "Tout le palier Professionnel",
        "Gestion d'équipe (jusqu'à 5)",
        "Image de marque et URL personnalisées",
        "Gestionnaire de compte dédié",
      ],
    },
  },
];

export const pricingComparisonRows = [
  {
    key: "ats",
    label: { en: "ATS optimization", fr: "Optimisation ATS" },
    basic: "partial",
    essential_advanced: true,
    professional: true,
    elite: true,
  },
  {
    key: "resume_enhancement",
    label: { en: "Résumé enhancement", fr: "Amélioration CV" },
    basic: "partial",
    essential_advanced: true,
    professional: true,
    elite: true,
  },
  {
    key: "formatting",
    label: { en: "Structured formatting", fr: "Mise en forme structurée" },
    basic: true,
    essential_advanced: true,
    professional: true,
    elite: true,
  },
  {
    key: "keywords",
    label: { en: "Keyword optimization", fr: "Optimisation mots-clés" },
    basic: "partial",
    essential_advanced: true,
    professional: true,
    elite: true,
  },
  {
    key: "cover_letter",
    label: { en: "Cover letter support", fr: "Lettre de motivation" },
    basic: false,
    essential_advanced: true,
    professional: true,
    elite: true,
  },
  {
    key: "turnaround",
    label: { en: "Faster turnaround", fr: "Délai accéléré" },
    basic: false,
    essential_advanced: true,
    professional: "partial",
    elite: true,
  },
  {
    key: "revisions",
    label: { en: "Free edits included", fr: "Révisions gratuites" },
    basic: "1",
    essential_advanced: "2 limited",
    professional: "2",
    elite: "3",
  },
];

export const performanceStats = {
  en: [
    { value: "Stripe", label: "Secure checkout", detail: "Hosted payments and TLS end-to-end." },
    { value: "ATS+", label: "Export discipline", detail: "PDF/DOC tuned for hiring stacks." },
    { value: "EN/FR", label: "Bilingual delivery", detail: "One studio cadence across markets." },
  ],
  fr: [
    { value: "Stripe", label: "Paiement sécurisé", detail: "Encaissement hébergé et TLS de bout en bout." },
    { value: "ATS+", label: "Discipline d’export", detail: "PDF/DOC alignés aux stacks recruteurs." },
    { value: "EN/FR", label: "Livraison bilingue", detail: "Une cadence studio sur vos marchés." },
  ],
};
